version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loje_virtual_mentoria
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: 
      - loja_virtual

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - loja_virtual

volumes:
  postgres:
  pgadmin:

networks:
  loja_virtual:
    driver: bridge
