version: '3.3'

services:
  mysql:
    image: mysql:8.0
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: password # Replace with your root password
      MYSQL_DATABASE: algafooddb
      MYSQL_USER: algafood
      MYSQL_PASSWORD: password
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
