logging:
  pattern:
    console: "[Kafka Other Demo] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
    application:
        name: kafka-other-demo
    main:
        banner-mode: off
        log-startup-info: false
