server:
  port: 8087

spring:
  application:
    name: ead
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      jdbc:
        time-zone: UTC
        lob.non_contextual_creation: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    com.auth-user: TRACE
    root: INFO
    # Caso precise de uma maior detalhamento da requisicao, altere o valor de INFO para DEBUG
    org.springframework.web: DEBUG
    # Caso precise de um maior detalhamento do SQL, altere o valor de INFO para DEBUG
    org.hibernate: INFO
