version: '3.3'

services:
  mysql:
    image: mysql:8.0
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: password # Replace with your root password
      MYSQL_DATABASE: bookdb
      MYSQL_USER: bookadmin
      MYSQL_PASSWORD: password
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3308
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: