networks:
  kafka-net:
    name: kafka-net
    driver: bridge
    external: true

services:
  postgresql-sample:
    image: postgres:16
    container_name: postgresql
    restart: unless-stopped
    networks:
      - kafka-net
    ports:
     - "5432:5432"
    volumes:
      - "./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres