version: "3"

services:
    engect-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sistema_engect
        environment:
            DATABASE_NAME: db-sistema-engect
            DATABASE_USER: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_HOST: db_engect
            DATABASE_PORT: 5432
            PORT: 8000
            DJANGO_SUPERUSER_USERNAME: admin
            DJANGO_SUPERUSER_EMAIL: admin@gmail.com
            DJANGO_SUPERUSER_PASSWORD: Teste@123
        volumes:
            - .:/app
        platform: linux/amd64 # caso não usando MACOS descomentar
        networks:
            - engect-net
        ports:
            - "8000:8000"

    db:
        image: postgres:16
        container_name: db_engect
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db-sistema-engect
        ports:
            - "5433:5432"
        networks:
            - engect-net

networks:
    engect-net:
        driver: bridge
