# Using a multi-stage build to keep the final image clean and secure
FROM --platform=linux/amd64 node:18

WORKDIR /app

COPY package*.json ./

RUN apt-get update && apt-get install -y ffmpeg

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]