version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alurafood-pagamento
      MYSQL_PASSWORD: root
    platform: linux/arm64/v8
    ports:
      - "3306:3306"
